// Legal Glossary — Urdu-English legal terms dictionary
// Each term includes: english term, urdu term, definition (en/ur), category

export type GlossaryTerm = {
  id: string
  term: string
  termUrdu: string
  pronunciation?: string
  definition: string
  definitionUrdu: string
  category: string
  categoryUrdu: string
}

export const glossaryTerms: GlossaryTerm[] = [
  // Criminal Law
  { id: 'fir', term: 'FIR', termUrdu: 'مقدمہِ اول', pronunciation: 'eff-eye-ar', definition: 'First Information Report — the initial complaint registered at a police station when a cognizable offence is reported. The FIR starts the formal criminal investigation.', definitionUrdu: 'پہلی معلوماتی رپورٹ — تھانے میں درج کی جانے والی ابتدائی شکایت جب قابلِ گرفتاری جرم کی اطلاع دی جائے۔ ایف آئی آر رسمی فوجداری تفتیش کا آغاز ہے۔', category: 'Criminal', categoryUrdu: 'فوجداری' },
  { id: 'bail', term: 'Bail', termUrdu: 'ضمانت', definition: 'The temporary release of an accused person awaiting trial, with a guarantee (surety) they will appear in court when required.', definitionUrdu: 'ملزم کی عارضی رہائی جو مقدمے کی سماعت کے دوران، اس شرط کے ساتھ کہ وہ عدالت کے بلانے پر حاضر ہوگا۔', category: 'Criminal', categoryUrdu: 'فوجداری' },
  { id: 'remand', term: 'Remand', termUrdu: 'تحویل', definition: 'The custody of an accused person, usually with the police for further investigation, granted by a magistrate for a limited period (commonly up to 14 days).', definitionUrdu: 'ملزم کی تحویل، عموماً مزید تفتیش کے لیے پولیس کے پاس، مجسٹریٹ کی طرف سے محدود مدت (عام طور پر 14 دن) کے لیے۔', category: 'Criminal', categoryUrdu: 'فوجداری' },
  { id: 'cognizable', term: 'Cognizable Offence', termUrdu: 'قابلِ گرفتاری جرم', definition: 'An offence for which police can arrest without a warrant and investigate without court permission. Examples: murder, theft, robbery.', definitionUrdu: 'ایسا جرم جس میں پولیس وارنٹ کے بغیر گرفتار کر سکتی ہے اور عدالت کی اجازت کے بغیر تفتیش کر سکتی ہے۔ مثال: قتل، چوری، ڈکیتی۔', category: 'Criminal', categoryUrdu: 'فوجداری' },
  { id: 'noncognizable', term: 'Non-Cognizable Offence', termUrdu: 'غیر قابلِ گرفتاری جرم', definition: 'An offence for which police cannot arrest without a warrant and require court permission to investigate. Examples: defamation, simple assault.', definitionUrdu: 'ایسا جرم جس میں پولیس وارنٹ کے بغیر گرفتار نہیں کر سکتی اور تفتیش کے لیے عدالت کی اجازت چاہیے۔ مثال: عزت آبری، سادہ حملہ۔', category: 'Criminal', categoryUrdu: 'فوجداری' },
  { id: 'bailable', term: 'Bailable Offence', termUrdu: 'ضمانت کے قابل جرم', definition: 'An offence where bail is a matter of right and the police or court must grant bail.', definitionUrdu: 'ایسا جرم جس میں ضمانت حق کے طور پر ملتی ہے اور پولیس یا عدالت ضمانت دینے کی پابند ہے۔', category: 'Criminal', categoryUrdu: 'فوجداری' },
  { id: 'qisas', term: 'Qisas', termUrdu: 'قصاص', definition: 'Retaliation in kind — the Islamic principle of "an eye for an eye" applied in murder cases. The victim\'s family may pardon the offender or accept diyat (blood money) instead.', definitionUrdu: 'برابر بدلہ — قتل کے معاملات میں لاگو اسلامی اصول "آنکھ کے بدلے آنکھ"۔ متاثرہ کا خاندان مجرم کو معاف کر سکتا ہے یا دیت قبول کر سکتا ہے۔', category: 'Criminal', categoryUrdu: 'فوجداری' },
  { id: 'diyat', term: 'Diyat', termUrdu: 'دیت', definition: 'Blood money paid to the victim\'s heirs in cases of murder or bodily harm, as an alternative to qisas (retaliation).', definitionUrdu: 'قتل یا جسمانی نقصان کے معاملات میں متاثرہ کے ورثاء کو ادا کی جانے والی خون بہا، قصاص کے متبادل کے طور پر۔', category: 'Criminal', categoryUrdu: 'فورداری' },
  { id: 'tazir', term: 'Ta\'zir', termUrdu: 'تعزیر', definition: 'Discretionary punishment determined by the judge, as opposed to the fixed punishments of hudood or qisas.', definitionUrdu: 'جج کے ذریعے مقرر کردہ صوابدیدی سزا، حد یا قصاص کی مقررہ سزاؤں کے برعکس۔', category: 'Criminal', categoryUrdu: 'فوجداری' },

  // Civil Law
  { id: 'decree', term: 'Decree', termUrdu: 'حکم نامہ', definition: 'The formal expression of a civil court\'s decision that determines the rights of the parties in a suit.', definitionUrdu: 'دیوانی عدالت کے فیصلے کی باقاعدہ عبارت جو دعوے میں فریقین کے حقوق کا تعین کرتی ہے۔', category: 'Civil', categoryUrdu: 'دیوانی' },
  { id: 'plaint', term: 'Plaint', termUrdu: 'دعوے کی درخواست', definition: 'The written statement filed by the plaintiff to initiate a civil lawsuit, stating the facts and the relief sought.', definitionUrdu: 'دیوانی مقدمہ شروع کرنے کے لیے مدعی کی طرف سے پیش کردہ تحریری بیان، جس میں حقائق اور مطالبہ درج ہوتا ہے۔', category: 'Civil', categoryUrdu: 'دیوانی' },
  { id: 'defendant', term: 'Defendant', termUrdu: 'مدعی علیہ', definition: 'The party against whom a civil lawsuit is filed or a criminal charge is brought.', definitionUrdu: 'وہ فریق جس کے خلاف دیوانی دعوا یا فوجداری الزام درج کیا گیا ہو۔', category: 'Civil', categoryUrdu: 'دیوانی' },
  { id: 'suit', term: 'Suit', termUrdu: 'دعویٰ', definition: 'A civil proceeding instituted by the plaintiff against one or more defendants, seeking legal remedy.', definitionUrdu: 'دیوانی کارروائی جو مدعی کی طرف سے ایک یا زیادہ مدعی علیہ کے خلاف قانونی چارہ جوئی کے لیے شروع کی جائے۔', category: 'Civil', categoryUrdu: 'دیوانی' },
  { id: 'injunction', term: 'Injunction', termUrdu: 'احکامِ حائل', definition: 'A court order restraining a party from doing a specific act (injunctive relief) or compelling them to do an act.', definitionUrdu: 'عدالتی حکم جو کسی فریق کو کسی مخصوص عمل سے روکتا ہے یا کسی عمل کے کرنے پرمجبور کرتا ہے۔', category: 'Civil', categoryUrdu: 'دیوانی' },

  // Family Law
  { id: 'nikah', term: 'Nikah', termUrdu: 'نکاح', definition: 'The Islamic marriage contract. Must be registered under the Muslim Family Laws Ordinance 1961.', definitionUrdu: 'اسلامی شادی کا معاہدہ۔ مسلم فیملی لاز آرڈیننس 1961 کے تحت رجسٹر ہونا ضروری ہے۔', category: 'Family', categoryUrdu: 'خاندانی' },
  { id: 'talaq', term: 'Talaq', termUrdu: 'طلاق', definition: 'Divorce initiated by the husband. Requires written notice to the Union Council Chairman and a 90-day waiting period (iddat) under MFLO 1961.', definitionUrdu: 'شوہر کی طرف سے طلاق۔ یونین کونسل چیئرمین کو تحریری اطلاع اور 90 دن کا انتظار (عده) لازم۔', category: 'Family', categoryUrdu: 'خاندانی' },
  { id: 'khula', term: 'Khula', termUrdu: 'خلع', definition: 'Divorce initiated by the wife, where she returns the dower (mahr) to the husband. Granted by the Family Court under the Family Courts Act 1964.', definitionUrdu: 'بیوی کی طرف سے طلاق، جس میں وہ مہر شوہر کو واپس کرتی ہے۔ فیملی کورٹس ایکٹ 1964 کے تحت فیملی کورٹ عطا کرتی ہے۔', category: 'Family', categoryUrdu: 'خاندانی' },
  { id: 'mahr', term: 'Mahr (Dower)', termUrdu: 'مہر', definition: 'The amount the husband agrees to pay the wife at the time of marriage. Becomes payable immediately or on divorce, as agreed in the nikahnama.', definitionUrdu: 'وہ رقم جو شوہر شادی کے وقت بیوی کو ادا کرنے کا پابند ہوتا ہے۔ فوراً یا طلاق پر قابلِ ادا، نکاح نامے کے مطابق۔', category: 'Family', categoryUrdu: 'خاندانی' },
  { id: 'iddat', term: 'Iddat', termUrdu: 'عده', definition: 'The waiting period a woman must observe after divorce or widowhood — three menstrual cycles (or three months) for divorce, four months and ten days for widowhood.', definitionUrdu: 'طلاق یا بیوگی کے بعد عورت کا انتظار کا عرصہ — طلاق کے لیے تین حیض کے دور (یا تین ماہ)، بیوگی کے لیے چار ماہ اور دس دن۔', category: 'Family', categoryUrdu: 'خاندانی' },
  { id: 'hizanat', term: 'Hizanat (Custody)', termUrdu: 'حضانت', definition: 'The right to physical custody of a minor. Generally the mother has custody of young children; the father is the natural guardian.', definitionUrdu: 'نابالغ کی جسمانی تحویل کا حق۔ عموماً ماں کو چھوٹے بچوں کی حضانت ہوتی ہے؛ باپ قدرتی سرپرست ہوتا ہے۔', category: 'Family', categoryUrdu: 'خاندانی' },
  { id: 'fasakh', term: 'Faskh', termUrdu: 'فسخ', definition: 'Judicial dissolution of marriage by a court on specific grounds (e.g. husband missing, cruelty, impotency), under the Dissolution of Muslim Marriages Act 1939.', definitionUrdu: 'عدالت کی طرف سے مخصوص بنیادوں پر شادی کا تحلیل (مثلاً شوہر لاپتا، ظلم، نامردی)، Dissolution of Muslim Marriages Act 1939 کے تحت۔', category: 'Family', categoryUrdu: 'خاندانی' },

  // Property Law
  { id: 'mutation', term: 'Mutation', termUrdu: 'انتقال', definition: 'The recording of a change in ownership of land in the revenue records (patwari/mutation register). Not itself a title document but evidence of transfer.', definitionUrdu: 'اراضی کی ملکیت میں تبدیلی کا ریونیو ریکارڈز (پٹواری/منتظم رجسٹر) میں اندراج۔ خود عنوان کی دستاویز نہیں مگر منتقلی کا ثبوت۔', category: 'Property', categoryUrdu: 'جائداد' },
  { id: 'intqaal', term: 'Intqaal', termUrdu: 'انتقال', definition: 'The Urdu term for "mutation" — the official record of change in land ownership maintained by the patwari.', definitionUrdu: '"متبادل" کا اردو اصطلاح — زمین کی ملکیت میں تبدیلی کا سرکاری ریکارڈ جو پٹواری برقرار رکھتا ہے۔', category: 'Property', categoryUrdu: 'جائداد' },
  { id: 'fard', term: 'Fard Malkiat', termUrdu: 'فرد ملکیت', definition: 'A revenue department document showing ownership of a piece of land. Issued by the patwari.', definitionUrdu: 'ریونیو محکمے کی دستاویز جو کسی زمین کی ملکیت دکھاتی ہے۔ پٹواری کی طرف سے جاری۔', category: 'Property', categoryUrdu: 'جائداد' },
  { id: 'tord', term: 'Tord (Registry)', termUrdu: 'تعدیل', definition: 'The formal registration of a sale deed (bay-nama) of property with the Sub-Registrar under the Registration Act 1908.', definitionUrdu: 'رجسٹریشن ایکٹ 1908 کے تحت سب رجسٹرار کے پاس بیع نامہ کا باقاعدہ اندراج۔', category: 'Property', categoryUrdu: 'جائداد' },

  // Court / Procedure
  { id: 'adalkat', term: 'Adalat', termUrdu: 'عدالت', definition: 'Court. Various types exist: Supreme Court (Siprime Kachehri), High Court, Sessions Court, Civil Court, Family Court, Magistrate Court.', definitionUrdu: 'عدالت۔ مختلف اقسام: سپریم کورٹ، ہائی کورٹ، سیشن کورٹ، سول کورٹ، فیملی کورٹ، مجسٹریٹ کورٹ۔', category: 'Court', categoryUrdu: 'عدالتی' },
  { id: 'wasi', term: 'Wasi/Vakil (Lawyer)', termUrdu: 'وکیل', definition: 'A licensed legal practitioner who represents clients in court. Must be enrolled with the relevant Bar Council (PBC or provincial).', definitionUrdu: 'لائسنس یافتہ قانونی پریکٹیشنر جو عدالت میں موکلین کی نمائندگی کرتا ہے۔ متعلقہ بار کونسل (پی بی سی یا صوبائی) میں داخلہ لازم۔', category: 'Court', categoryUrdu: 'عدالتی' },
  { id: 'mukhtar', term: 'Mukhtar (Power of Attorney)', termUrdu: 'مختار', definition: 'A person authorized to act on behalf of another through a Power of Attorney document.', definitionUrdu: 'وہ شخص جسے پاور آف اٹارنی دستاویز کے ذریعے کسی دوسرے کی طرف سے کام کرنے کا اختیار حاصل ہے۔', category: 'Court', categoryUrdu: 'عدالتی' },
  { id: 'appeal', term: 'Appeal', termUrdu: 'اپیل', definition: 'A request to a higher court to review and change the decision of a lower court.', definitionUrdu: 'اعلیٰ عدالت سے نچلی عدالت کے فیصلے کی نظر ثانی اور تبدیلی کی درخواست۔', category: 'Court', categoryUrdu: 'عدالتی' },
  { id: 'writ', term: 'Writ Petition', termUrdu: 'رٹ درخواست', definition: 'A petition to the High Court (Art. 199) or Supreme Court (Art. 184) for enforcement of fundamental rights or to challenge government action.', definitionUrdu: 'بنیادی حقوق کے نفاذ یا حکومتی اقدام کو چیلنج کرنے کے لیے ہائی کورٹ (آرٹیکل 199) یا سپریم کورٹ (آرٹیکل 184) میں درخواست۔', category: 'Court', categoryUrdu: 'عدالتی' },

  // Constitutional
  { id: 'fundamental-rights', term: 'Fundamental Rights', termUrdu: 'بنیادی حقوق', definition: 'The basic rights guaranteed to all citizens under Articles 8–28 of the Constitution of Pakistan 1973, including life, liberty, equality, freedom of speech, religion.', definitionUrdu: 'آئینِ پاکستان 1973 کے آرٹیکل 8-28 کے تحت تمام شہریوں کو یقینی بنیادی حقوق، بشمول زندگی، آزادی، مساوات، تقریر، مذہب کی آزادی۔', category: 'Constitutional', categoryUrdu: 'آئینی' },
  { id: 'suo-motu', term: 'Suo Motu', termUrdu: 'سو موٹو', definition: 'A court taking up a matter on its own motion (without a formal petition), typically for issues of public importance or fundamental rights violation.', definitionUrdu: 'عدالت کا کسی معاملے کو اپنی خودmalsuusanشروع کرنا (بغیر رسمی درخواست)، عموماً عوامی اہمیت یا بنیادی حقوق کی خلاف ورزی کے معاملات میں۔', category: 'Constitutional', categoryUrdu: 'آئینی' },
  { id: 'ordinance', term: 'Ordinance', termUrdu: 'آرڈیننس', definition: 'A law promulgated by the President (federal) or Governor (provincial) when the legislature is not in session. Must be approved by Parliament/Assembly within 4 months to remain in force.', definitionUrdu: 'وہ قانون جو صدر (وفاقی) یا گورنر (صوبائی) جب مقننہ غیر حاضر ہو، نافذ کرے۔ پارلیمنٹ/اسمبلی کی منظوری 4 ماہ میں لازم۔', category: 'Constitutional', categoryUrdu: 'آئینی' },
  { id: 'act', term: 'Act', termUrdu: 'ایکٹ', definition: 'A law passed by the Parliament or a Provincial Assembly. Becomes operative after Presidential/Governor assent.', definitionUrdu: 'پارلیمنٹ یا صوبائی اسمبلی کا پاس کردہ قانون۔ صدر/گورنر کی منظوری کے بعد نافذ۔', category: 'Constitutional', categoryUrdu: 'آئینی' },
  { id: 'amendment', term: 'Amendment', termUrdu: 'ترمیم', definition: 'A formal change or addition to an existing law or the Constitution. Constitutional amendments require 2/3 majority in Parliament.', definitionUrdu: 'موجودہ قانون یا آئین میں باقاعدہ تبدیلی یا اضافہ۔ آئینی ترامیم کے لیے پارلیمنٹ میں دو تہائی اکثریت لازم۔', category: 'Constitutional', categoryUrdu: 'آئینی' },

  // Tax / Business
  { id: 'filer', term: 'Filer', termUrdu: 'فائلر', definition: 'A person who appears on the Active Taxpayer List (ATL) of the FBR. Filers enjoy lower withholding tax rates.', definitionUrdu: 'وہ شخص جو FBR کی ایکٹو ٹیکس پیر لسٹ (ATL) میں شامل ہو۔ فائلرز کو کم وِلڈنگ ٹیکس کی شرح ملتی ہے۔', category: 'Tax', categoryUrdu: 'ٹیکس' },
  { id: 'nonfiler', term: 'Non-Filer', termUrdu: 'نان فائلر', definition: 'A person not on the FBR\'s Active Taxpayer List. Subject to higher withholding tax rates on transactions.', definitionUrdu: 'وہ شخص جو FBR کی ایکٹو ٹیکس پیر لسٹ میں نہیں۔ لین دین پر زیادہ وِلڈنگ ٹیکس کا پابند۔', category: 'Tax', categoryUrdu: 'ٹیکس' },
  { id: 'withholding-tax', term: 'Withholding Tax', termUrdu: 'وِلڈنگ ٹیکس', definition: 'Tax deducted at source by the payer before making a payment (salary, rent, contractor). The recipient can adjust it against their final tax liability.', definitionUrdu: 'ادا کرنے والے کی طرف سے ادائیگی سے پہلے منقطع کیا جانے والا ٹیکس (تنخواہ، کرایہ، ٹھیکیدار)۔ وصول کنندہ اپنی آخری ٹیکس ذمہ داری کے خلاف ایڈجسٹ کر سکتا ہے۔', category: 'Tax', categoryUrdu: 'ٹیکس' },
  { id: 'assessment', term: 'Assessment', termUrdu: 'تشخیص', definition: 'The process by which the FBR determines a taxpayer\'s taxable income and tax liability for a tax year.', definitionUrdu: 'وہ عمل جس کے ذریعے FBR کسی ٹیکس دہندہ کے قابلِ ٹیکس آمدنی اور ٹیکسی سال کے لیے ٹیکس ذمہ داری کا تعین کرتا ہے۔', category: 'Tax', categoryUrdu: 'ٹیکس' },
  { id: 'return', term: 'Tax Return', termUrdu: 'ٹیکس ریٹرن', definition: 'The annual statement filed with the FBR declaring income, deductions, and tax paid. Mandatory for filers.', definitionUrdu: 'FBR کے ساتھ داخل کردہ سالانہ بیان جس میں آمدنی، کٹوتیاں، اور ادا شدہ ٹیکس درج ہوتے ہیں۔ فائلرز کے لیے لازمی۔', category: 'Tax', categoryUrdu: 'ٹیکس' },

  // Cyber
  { id: 'cybercrime', term: 'Cyber Crime', termUrdu: 'سائبر کرائم', definition: 'A crime committed using a computer, network, or information system. In Pakistan, governed by the Prevention of Electronic Crimes Act (PECA) 2016.', definitionUrdu: 'کمپیوٹر، نیٹ ورک، یا معلوماتی نظام کا استعمال کرتے ہوئے کیا گیا جرم۔ پاکستان میں PECA 2016 کے تحت منظم۔', category: 'Cyber', categoryUrdu: 'سائبر' },
  { id: 'hacking', term: 'Unauthorized Access', termUrdu: 'غیر مجاز رسائی', definition: 'Gaining access to an information system or data without permission. Criminalized under Section 3 of PECA 2016, punishable up to 3 months imprisonment.', definitionUrdu: 'بغیر اجازت کسی معلوماتی نظام یا ڈیٹا تک رسائی حاصل کرنا۔ PECA 2016 کی شق 3 کے تحت جرم، تین ماہ قید تک سزا۔', category: 'Cyber', categoryUrdu: 'سائبر' },
  { id: 'phishing', term: 'Phishing / Fraud', termUrdu: 'فشنگ / فراڈ', definition: 'Deceiving someone into revealing sensitive information (passwords, bank details) through fake emails, websites, or messages.', definitionUrdu: 'جعلی ای میلز، ویب سائٹس، یا پیغامات کے ذریعے حساس معلومات (پاس ورڈز، بینک تفصیلات) ظاہر کرنے پر کسی کو دھوکے میں مبتلا کرنا۔', category: 'Cyber', categoryUrdu: 'سایبر' },
  { id: 'e-signature', term: 'Electronic Signature', termUrdu: 'الیکٹرانک دستخط', definition: 'A signature in electronic form, legally recognized under the Electronic Transactions Ordinance 2002. Has the same legal validity as a handwritten signature.', definitionUrdu: 'الیکٹرانک شکل میں دستخط، الیکٹرانک ٹرانزیکشنز آرڈیننس 2002 کے تحت قانونی حیثیت رکھتا ہے۔ ہاتھ سے لکھے دستخط کی طرح قانونی قدر۔', category: 'Cyber', categoryUrdu: 'سائبر' },

  // Evidence
  { id: 'shahadat', term: 'Shahadat (Evidence)', termUrdu: 'شہادت', definition: 'Testimony or evidence presented in court. Governed in Pakistan by the Qanun-e-Shahadat Order 1984.', definitionUrdu: 'عدالت میں پیش کی جانے والی گواہی یا ثبوت۔ پاکستان میں قانونِ شہادت آرڈر 1984 کے تحت منظم۔', category: 'Evidence', categoryUrdu: 'ثبوت' },
  { id: 'gawah', term: 'Gawah (Witness)', termUrdu: 'گواہ', definition: 'A person who testifies in court. Must be competent (Article 17 of QSO 1984) — generally every person is competent unless the court decides otherwise.', definitionUrdu: 'وہ شخص جو عدالت میں گواہی دیتا ہے۔ اہل ہونا لازم (قانونِ شہادت آرڈر 1984 کا آرٹیکل 17) — عموماً ہر شخص اہل ہے جب تک عدالت فیصلہ نہ کرے۔', category: 'Evidence', categoryUrdu: 'ثبوت' },
  { id: 'circumstantial', term: 'Circumstantial Evidence', termUrdu: 'حالاتِ واقعہ کا ثبوت', definition: 'Evidence that indirectly proves a fact, by inference from other facts. Insufficient alone for a conviction unless it forms a complete chain.', definitionUrdu: 'ایسا ثبوت جو بالواسطہ کسی حقیقت کو ثابت کرتا ہے، دیگر حقائق سے استدلال کے ذریعے۔ تنہا سزا کے لیے ناکافی جب تک مکمل سلسلہ نہ بنائے۔', category: 'Evidence', categoryUrdu: 'ثبوت' },

  // Labor
  { id: 'muzdoor', term: 'Mazdoor (Worker)', termUrdu: 'مزدور', definition: 'A worker or employee. Legal protections under the Industrial Relations Act 2012, Factories Act 1934, and provincial labor laws.', definitionUrdu: 'مزدور یا ملازم۔ انڈسٹریل ریلیشنز ایکٹ 2012، فیکٹریز ایکٹ 1934 اور صوبائی محنت قوانین کے تحت قانونی تحفظات۔', category: 'Labor', categoryUrdu: 'محنت' },
  { id: 'najranah', term: 'Wages', termUrdu: 'اجرت', definition: 'Remuneration paid to a worker for work done. Governed by the Payment of Wages Act 1936 (timing) and Minimum Wages Ordinance 1961 (rate).', definitionUrdu: 'مزدور کو کیے گئے کام کے بدلے میں ادا کی جانے والی معاوضہ۔ پیمنٹ آف ویجز ایکٹ 1936 (وقت) اور مینی مم ویجز آرڈیننس 1961 (شرح) کے تحت۔', category: 'Labor', categoryUrdu: 'محنت' },
  { id: 'hartal', term: 'Strike (Hartal)', termUrdu: 'ہڑتال', definition: 'A work stoppage by employees as a form of protest. Regulated under the Industrial Relations Act 2012 — requires notice and conciliation attempts.', definitionUrdu: 'مزدوروں کا احتجاج کے طور پر کام بند کرنا۔ انڈسٹریل ریلیشنز ایکٹ 2012 کے تحت منظم — اطلاع اور مصالحت کی کوشش لازم۔', category: 'Labor', categoryUrdu: 'محنت' },

  // General legal
  { id: 'wasiyat', term: 'Wasiyat (Will)', termUrdu: 'وصیت', definition: 'A testamentary document stating how a person\'s property should be distributed after death. Under Muslim law, up to 1/3 of the estate can be willed.', definitionUrdu: 'وصیتی دستاویز جس میں بتایا جائے کہ موت کے بعد جائداد کی تقسیم کیسے ہو۔ مسلم قانون کے تحت، ترکے کا ایک تہائی وصیت کیا جا سکتا ہے۔', category: 'Property', categoryUrdu: 'جائداد' },
  { id: 'verasat', term: 'Verasaat (Inheritance)', termUrdu: 'وراثت', definition: 'The share of a deceased person\'s estate passing to heirs. In Pakistan, Muslim inheritance is governed by Islamic law (Sharia), codified in various statutes.', definitionUrdu: 'متوفی کے ترکے کا حصہ جو ورثاء کو منتقل ہوتا ہے۔ پاکستان میں مسلم وراثت اسلامی قانون (شریعت) کے تحت، مختلف قوانین میں ضبط۔', category: 'Property', categoryUrdu: 'جائداد' },
  { id: 'aqd', term: 'Aqd (Contract)', termUrdu: 'عقد', definition: 'A legally binding agreement between parties. Governed by the Contract Act 1872.', definitionUrdu: 'فریقین کے درمیان قانونی پابند معاہدہ۔ کنٹریکٹ ایکٹ 1872 کے تحت۔', category: 'Civil', categoryUrdu: 'دیوانی' },

  // Banking & Finance
  { id: 'cheque-bounce', term: 'Cheque Bounce', termUrdu: 'چیک باؤنس', definition: 'When a bank refuses to honor a cheque due to insufficient funds or other reasons. Criminalized under Section 138 of the Negotiable Instruments Act 1881, punishable with up to 2 years imprisonment.', definitionUrdu: 'جب بینک کسی چیک کو ناکافی رقم یا دیگر وجوہات کی بنا پر اد نہیں کرتا۔ قابلِ تبادلہ آلات ایکٹ 1881 کی شق 138 کے تحت جرم، 2 سال تک قید کی سزا۔', category: 'Tax', categoryUrdu: 'ٹیکس' },
  { id: 'naqal-haq', term: 'Naql-e-Haq (Assignment)', termUrdu: 'نقلِ حق', definition: 'The transfer of a right or interest from one person to another, typically used in the context of receivables, contracts, or intellectual property.', definitionUrdu: 'کسی حق یا مفاد کا ایک شخص سے دوسرے شخص کو منتقل، عموماً وصولیوں، معاہدوں، یا دانش مندانی حقوق کے حوالے سے۔', category: 'Civil', categoryUrdu: 'دیوانی' },

  // Corporate
  { id: 'secp', term: 'SECP', termUrdu: 'ایس ای سی پی', definition: 'Securities and Exchange Commission of Pakistan — the regulatory body for companies, insurance, and capital markets in Pakistan. Established under the SECP Act 1997.', definitionUrdu: 'سیکیورٹیز اینڈ ایکسچینج کمیشن آف پاکستان — کمپنیوں، انشورنس، اور سرمایہ کار بازاروں کا ریگولیٹری ادارہ۔ SECP ایکٹ 1997 کے تحت قائم۔', category: 'Court', categoryUrdu: 'عدالتی' },
  { id: 'mudaraba', term: 'Mudaraba', termUrdu: 'مضاربہ', definition: 'An Islamic financial partnership where one party provides capital (rabb-ul-mal) and the other manages the business (mudarib). Profits are shared per agreed ratio; losses borne by the capital provider.', definitionUrdu: 'اسلامی مالی شراکت جہاں ایک فریق سرمایہ فراہم کرتا ہے اور دوسرا کاروبار چلاتا ہے۔ منافع متفقہ تناسب سے تقسیم؛ نقصان سرمایہ دہندہ برداشت کرتا ہے۔', category: 'Tax', categoryUrdu: 'ٹیکس' },
  { id: 'musharaka', term: 'Musharaka', termUrdu: 'مشارکہ', definition: 'An Islamic financial partnership where all partners contribute capital and share profits and losses according to agreed ratios. Used in Islamic banking and joint ventures.', definitionUrdu: 'اسلامی مالی شراکت جہاں تمام شرکاء سرمایہ فراہم کرتے ہیں اور منافع و نقصان متفقہ تناسب سے تقسیم کرتے ہیں۔ اسلامی بینکاری اور مشترکہ منصوبوں میں استعمال۔', category: 'Tax', categoryUrdu: 'ٹیکس' },

  // Election
  { id: 'ecp', term: 'ECP', termUrdu: 'ای سی پی', definition: 'Election Commission of Pakistan — the constitutional body responsible for conducting elections. Established under Article 215 of the Constitution and the Elections Act 2017.', definitionUrdu: 'الیکشن کمیشن آف پاکستان — الیکشن کے انعقاد کا آئینی ادارہ۔ آئین کے آرٹیکل 215 اور الیکشنز ایکٹ 2017 کے تحت قائم۔', category: 'Constitutional', categoryUrdu: 'آئینی' },
  { id: 'halqa-bandi', term: 'Halqa Bandi (Delimitation)', termUrdu: 'حلقہ بندی', definition: 'The process of demarcating electoral constituencies. In Pakistan, done by the ECP before each general election based on the latest census data.', definitionUrdu: 'الیکشن حلقوں کی حد بندی کا عمل۔ پاکستان میں، ECP ہر عام الیکشن سے قبل تازہ ترین مردم شماری کی بنیاد پر کرتا ہے۔', category: 'Constitutional', categoryUrdu: 'آئینی' },

  // Immigration
  { id: 'nadra', term: 'NADRA', termUrdu: 'نادرا', definition: 'National Database and Registration Authority — the Pakistani government agency responsible for issuing CNICs (identity cards), passports, and maintaining the national citizen database.', definitionUrdu: 'نیشنل ڈیٹابیس اینڈ رجسٹریشن اتھارٹی — پاکستانی حکومتی ادارہ جو شناختی کارڈز، پاسپورٹس، اور قومی شہری ڈیٹابیس کی دیکھ بھال کرتا ہے۔', category: 'Court', categoryUrdu: 'عدالتی' },
  { id: 'cnic', term: 'CNIC', termUrdu: 'شناختی کارڈ', definition: 'Computerized National Identity Card — the primary identity document for Pakistani citizens aged 18 and above, issued by NADRA.', definitionUrdu: 'کمپیوٹرائزڈ نیشنل آئیڈینٹیٹی کارڈ — 18 سال سے زیادہ عمر کے پاکستانی شہریوں کی بنیادی شناختی دستاویز، نادرا کی طرف سے جاری۔', category: 'Court', categoryUrdu: 'عدالتی' },

  // Health
  { id: 'drap', term: 'DRAP', termUrdu: 'ڈریپ', definition: 'Drug Regulatory Authority of Pakistan — the federal body that regulates therapeutic goods including drugs, medical devices, and cosmetics. Established under the DRAP Act 2012.', definitionUrdu: 'ڈرگ ریگولیٹری اتھارٹی آف پاکستان — وفاقی ادارہ جو دواؤں، طبی آلات، اور کاسمیٹکس کو منظم کرتا ہے۔ DRAP ایکٹ 2012 کے تحت قائم۔', category: 'Court', categoryUrdu: 'عدالتی' },
  { id: 'pmdc', term: 'PMDC/PMC', termUrdu: 'پی ایم ڈی سی/پی ایم سی', definition: 'Pakistan Medical & Dental Council / Pakistan Medical Commission — the regulatory body for medical and dental education and practice in Pakistan. Doctors must be registered to practice.', definitionUrdu: 'پاکستان میڈیکل و ڈینٹل کونسل / پاکستان میڈیکل کمیشن — پاکستان میں طبی و دانتانی تعلیم اور پریکٹس کا ریگولیٹری ادارہ۔ پریکٹس کے لیے ڈاکٹرز کی رجسٹری لازم۔', category: 'Court', categoryUrdu: 'عدالتی' },

  // Education
  { id: 'hec', term: 'HEC', termUrdu: 'ایچ ای سی', definition: 'Higher Education Commission of Pakistan — the regulatory body for universities and degree-awarding institutions. Sets standards, accredits programs, verifies degrees, and allocates funding.', definitionUrdu: 'ہائیر ایجوکیشن کمیشن آف پاکستان — یونیورسٹیز اور ڈگری دینے والے اداروں کا ریگولیٹری ادارہ۔ معیار مقرر کرتا ہے، پروگراموں کی تصدیق کرتا ہے، ڈگریز کی تصدیق کرتا ہے، فنڈ مختص کرتا ہے۔', category: 'Court', categoryUrdu: 'عدالتی' },

  // Traffic
  { id: 'driving-license', term: 'Driving License', termUrdu: 'ڈرائیونگ لائسنس', definition: 'An official document issued by the licensing authority permitting a person to drive a motor vehicle. Required under the Motor Vehicles Ordinance 1965. Types: learner, permanent, international.', definitionUrdu: 'لائسنسنگ اتھارٹی کی طرف سے جاری کردہ سرکاری دستاویز جو شخص کو موٹر گاڑی چلانے کی اجازت دیتی ہے۔ موٹر گاڑیاں آرڈیننس 1965 کے تحت لازم۔ اقسام: لرنر، مستقل، بین الاقوامی۔', category: 'Court', categoryUrdu: 'عدالتی' },

  // Environmental
  { id: 'epa', term: 'EPA', termUrdu: 'ای پی اے', definition: 'Environmental Protection Agency — the federal/provincial body responsible for implementing environmental laws in Pakistan. Established under the Pakistan Environmental Protection Act 1997.', definitionUrdu: 'انوائرمنٹل پروٹیکشن ایجنسی — پاکستان میں ماحولیاتی قوانین کے نفاذ کا وفاقی/صوبائی ادارہ۔ پاکستان انوائرمنٹل پروٹیکشن ایکٹ 1997 کے تحت قائم۔', category: 'Court', categoryUrdu: 'عدالتی' },
  { id: 'eia', term: 'EIA', termUrdu: 'ای آئی اے', definition: 'Environmental Impact Assessment — a mandatory study required under the Pakistan Environmental Protection Act 1997 before commencing any project likely to have adverse environmental impact.', definitionUrdu: 'انوائرمنٹل امپیکٹ اسیسمنٹ — پاکستان انوائرمنٹل پروٹیکشن ایکٹ 1997 کے تحت لازمی مطالعہ جو کسی منصوبے کے منفی ماحولیاتی اثرات کے امکان پر شروع کرنے سے قبل ضروری ہے۔', category: 'Environmental', categoryUrdu: 'ماحولیاتی' },

  // Insurance
  { id: 'takaful', term: 'Takaful', termUrdu: 'تکافل', definition: 'Islamic insurance — a Sharia-compliant alternative to conventional insurance based on mutual cooperation and shared responsibility. Regulated by the SECP under the Insurance Ordinance 2000.', definitionUrdu: 'اسلامی انشورنس — روایتی انشورنس کا شریعہ کے مطابق متبادل جو باہمی تعاون اور مشترکہ ذمہ داری پر مبنی ہے۔ SECP کے تحت انشورنس آرڈیننس 2000 کے ذریعے منظم۔', category: 'Tax', categoryUrdu: 'ٹیکس' },

  // Anti-Corruption
  { id: 'nab', term: 'NAB', termUrdu: 'این اے بی', definition: 'National Accountability Bureau — Pakistan\'s primary anti-corruption agency, established under the National Accountability Ordinance 1999. Investigates and prosecutes corruption cases.', definitionUrdu: 'نیشنل اکاؤنٹیبلٹی بیورو — پاکستان کی بنیادی اینٹی کرپشن ایجنسی، نیشنل اکاؤنٹیبلٹی آرڈیننس 1999 کے تحت قائم۔ بدعنوانی کے مقدمات کی تفتیش اور مقدمہ چلانے کا ذمہ دار۔', category: 'Court', categoryUrdu: 'عدالتی' },
  { id: 'plea-bargain', term: 'Plea Bargain', termUrdu: 'پلی بارگین', definition: 'A legal mechanism under Section 25 of the NAB Ordinance where an accused person offers to return the amount involved in the offence. If accepted by the NAB Chairman, the accused is discharged.', definitionUrdu: 'این اے بی آرڈیننس کی شق 25 کے تحت قانونی طریقہ جہاں ملزم جرم میں ملوث رقم واپس کرنے کی پیشکش کرتا ہے۔ اگر این اے بی چیئرمین قبول کرے، ملزم کو بری کر دیا جاتا ہے۔', category: 'Criminal', categoryUrdu: 'فوجداری' },

  // Arbitration
  { id: 'arbitrator', term: 'Arbitrator', termUrdu: 'ثالث', definition: 'A neutral third party appointed to resolve a dispute outside the court system. Governed by the Arbitration Act 1940 in Pakistan. The arbitrator\'s decision (award) is binding.', definitionUrdu: 'عدالت کے نظام سے باہر تنازعہ حل کرنے کے لیے مقرر کیا جانے والا غیر جانبدار تیسری فریق۔ پاکستان میں ثالثی ایکٹ 1940 کے تحت منظم۔ ثالث کا فیصلہ (ایوارڈ) پابند ہے۔', category: 'Civil', categoryUrdu: 'دیوانی' },
  { id: 'award', term: 'Arbitral Award', termUrdu: 'ثالثی ایوارڈ', definition: 'The final decision made by an arbitrator or arbitration tribunal. Under the Arbitration Act 1940, it can be enforced as a court decree after being filed in court.', definitionUrdu: 'ثالث یا ثالثی ٹریبیونل کا حتمی فیصلہ۔ ثالثی ایکٹ 1940 کے تحت، عدالت میں دائر کرنے کے بعد عدالتی حکم کے طور پر نافذ کیا جا سکتا ہے۔', category: 'Civil', categoryUrdu: 'دیوانی' },

  // Media
  { id: 'pemra', term: 'PEMRA', termUrdu: 'پیمرا', definition: 'Pakistan Electronic Media Regulatory Authority — the regulatory body for electronic media (TV, radio, OTT). Established under the PEMRA Ordinance 2002. Issues broadcast licenses and sets content standards.', definitionUrdu: 'پاکستان الیکٹرانک میڈیا ریگولیٹری اتھارٹی — الیکٹرانک میڈیا کا ریگولیٹری ادارہ۔ پیمرا آرڈیننس 2002 کے تحت قائم۔ نشریاتی لائسنس جاری کرتا ہے اور مواد کے معیارات مقرر کرتا ہے۔', category: 'Court', categoryUrdu: 'عدالتی' },

  // Human Rights
  { id: 'nchr', term: 'NCHR', termUrdu: 'این سی ایچ آر', definition: 'National Commission for Human Rights — an independent statutory body established under the NCHR Act 2012 to promote and protect human rights in Pakistan. Modeled on the UN Paris Principles.', definitionUrdu: 'نیشنل کمیشن برائے انسانی حقوق — پاکستان میں انسانی حقوق کی تشہیر اور تحفظ کے لیے آزاد قانونی ادارہ۔ این سی ایچ آر ایکٹ 2012 کے تحت قائم۔ اقوام متحدہ کے پیرس اصولوں پر مبنی۔', category: 'Constitutional', categoryUrdu: 'آئینی' },

  // General
  { id: 'wakalatnama', term: 'Wakalatnama', termUrdu: 'وکالت نامہ', definition: 'A formal engagement document signed between a client and a lawyer, authorizing the lawyer to represent the client in court. Also known as a power of attorney for legal representation.', definitionUrdu: 'موکل اور وکیل کے درمیان دستخط شدہ باقاعدہ دستاویز جو وکیل کو عدالت میں موکل کی نمائندگی کا اختیار دیتی ہے۔ قانونی نمائندگی کے لیے مختار نامہ بھی کہلاتا ہے۔', category: 'Court', categoryUrdu: 'عدالتی' },
  { id: 'tauheen', term: 'Tauheen-e-Risalat', termUrdu: 'توہینِ رسالت', definition: 'Blasphemy against the Prophet Muhammad (PBUH). Added to the PPC in 1986 as Section 295-C, punishable with death or life imprisonment. Highly sensitive in Pakistan.', definitionUrdu: 'پیغمبرِ اسلام کی توہین۔ 1986 میں PPC کی شق 295-C کے طور پر شامل، موت یا قیدِ بامشقت کی سزا۔ پاکستان میں انتہائی حساس۔', category: 'Criminal', categoryUrdu: 'فوجداری' },
  { id: 'hudood', term: 'Hudood', termUrdu: 'حدود', definition: 'Fixed punishments prescribed in the Quran for certain offences (theft, robbery, zina, qazf, drinking). Implemented in Pakistan via the Hudood Ordinances 1979. Distinguished from ta\'zir (discretionary punishments).', definitionUrdu: 'قرآن میں مخصوص جرائم (چوری، ڈکیتی، زنا، قذف، شراب) کے لیے مقررہ سزائیں۔ پاکستان میں حدود آرڈیننس 1979 کے ذریعے نافذ۔ تعزیر (صوابدیدی سزاؤں) سے ممتاز۔', category: 'Criminal', categoryUrdu: 'فوجداری' },
  { id: 'istefaa', term: 'Istefa (Resignation)', termUrdu: 'استعفا', definition: 'The formal act of voluntarily relinquishing a position or office. In the context of elected representatives, it must be submitted in writing to the relevant authority (Speaker/Chairman).', definitionUrdu: 'کسی عہدے یا ذمہ داری سے رضاکارانہ طور پر دستبرداری کا باقاعدہ عمل۔ منتخب نمائندوں کے حوالے سے، اسے تحریری طور پر متعلقہ اتھارٹی (اسپیکر/چیئرمین) کو پیش کرنا ہوتا ہے۔', category: 'Constitutional', categoryUrdu: 'آئینی' },
]
