import { NextRequest, NextResponse } from 'next/server'

// POST /api/templates/[slug]/generate — fill in template with field values
// Body: { values: { fieldName: value, ... }, lang: 'en' | 'ur', format: 'text' | 'html' | 'pdf' }
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params
  const body = await req.json()
  const values: Record<string, string> = body.values ?? {}
  const lang: 'en' | 'ur' = body.lang ?? 'en'
  const format: 'text' | 'html' | 'pdf' = body.format ?? 'text'

  // Dynamic import to avoid bundling Prisma in client requests
  const { db } = await import('@/lib/db')
  const tpl = await db.docTemplate.findUnique({ where: { slug } })
  if (!tpl) return NextResponse.json({ ok: false, error: 'Template not found' }, { status: 404 })

  const sourceText = lang === 'ur' && tpl.templateTextUrdu ? tpl.templateTextUrdu : tpl.templateText
  const fields = JSON.parse(tpl.fieldsJson as string) as Array<{
    key: string
    label: string
    type: string
    required?: boolean
  }>

  // Validate required fields
  for (const field of fields) {
    if (field.required && !values[field.key]?.trim()) {
      return NextResponse.json(
        { ok: false, error: `Required field "${field.label}" is missing`, field: field.key },
        { status: 400 }
      )
    }
  }

  // Replace placeholders {{fieldName}} with values
  let filled = sourceText
  for (const [key, val] of Object.entries(values)) {
    const safeVal = (val ?? '').toString()
    filled = filled.replace(new RegExp(`\\{\\{\\s*${key}\\s*\\}\\}`, 'g'), safeVal)
  }
  // Replace any unfilled placeholders with [______]
  filled = filled.replace(/\{\{\s*[a-zA-Z0-9_]+\s*\}\}/g, '[______]')

  // If PDF format requested, generate PDF using jsPDF
  if (format === 'pdf') {
    try {
      const { jsPDF } = await import('jspdf')
      const isUrdu = lang === 'ur'
      const doc = new jsPDF({
        unit: 'pt',
        format: 'a4',
        orientation: 'portrait',
      })

      const pageWidth = doc.internal.pageSize.getWidth()
      const pageHeight = doc.internal.pageSize.getHeight()
      const margin = 50
      const maxWidth = pageWidth - 2 * margin

      // Title
      doc.setFontSize(16)
      doc.setFont('helvetica', 'bold')
      const title = isUrdu ? (tpl.titleUrdu ?? tpl.title) : tpl.title
      const titleLines = doc.splitTextToSize(title, maxWidth)
      doc.text(titleLines, pageWidth / 2, margin + 20, { align: 'center' })

      // Horizontal line under title
      doc.setLineWidth(1)
      doc.setDrawColor(13, 148, 136) // primary emerald
      doc.line(margin, margin + 40, pageWidth - margin, margin + 40)

      // Body content
      doc.setFontSize(11)
      doc.setFont('helvetica', 'normal')
      const lines = doc.splitTextToSize(filled, maxWidth)
      let y = margin + 65
      const lineHeight = 16
      for (const line of lines) {
        if (y > pageHeight - margin - 40) {
          doc.addPage()
          y = margin + 20
        }
        doc.text(line, margin, y)
        y += lineHeight
      }

      // Footer
      const pageCount = doc.getNumberOfPages()
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.setFont('helvetica', 'italic')
        doc.setTextColor(120)
        const footerText = isUrdu
          ? 'قانون پی کے — پاکستان قانونی ڈائریکٹری کے ذریعے تیار کردہ | یہ قانونی مشورہ نہیں ہے۔'
          : 'Generated by QanoonPK — Pakistan Legal Directory | This is not legal advice. Consult a licensed lawyer.'
        doc.text(footerText, pageWidth / 2, pageHeight - 25, { align: 'center' })
        doc.setTextColor(180)
        doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 12, { align: 'center' })
        doc.setTextColor(0) // reset
      }

      const pdfBuffer = doc.output('arraybuffer')
      return new NextResponse(pdfBuffer, {
        status: 200,
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="${slug}-${Date.now()}.pdf"`,
        },
      })
    } catch (e) {
      console.error('PDF generation error:', e)
      return NextResponse.json({ ok: false, error: 'PDF generation failed' }, { status: 500 })
    }
  }

  // If HTML format requested, wrap in styled HTML
  if (format === 'html') {
    const isUrdu = lang === 'ur'
    const html = `<!DOCTYPE html>
<html lang="${isUrdu ? 'ur' : 'en'}" dir="${isUrdu ? 'rtl' : 'ltr'}">
<head>
<meta charset="utf-8" />
<title>${tpl.title}</title>
<style>
  body { font-family: ${isUrdu ? "'Noto Nastaliq Urdu', serif" : "'Times New Roman', Georgia, serif"}; line-height: 1.8; max-width: 800px; margin: 40px auto; padding: 20px; color: #111; }
  h1 { text-align: center; border-bottom: 2px solid #0d9488; padding-bottom: 12px; }
  p, li { font-size: 14px; }
  .signature-line { display: inline-block; border-bottom: 1px solid #000; min-width: 200px; padding: 0 20px; }
  .footer { margin-top: 50px; padding-top: 20px; border-top: 1px dashed #999; font-size: 11px; color: #666; text-align: center; }
  @media print { body { margin: 0; padding: 30px; } }
</style>
</head>
<body>
<pre style="white-space: pre-wrap; font-family: inherit;">${filled}</pre>
<div class="footer">
  Generated by QanoonPK — Pakistan Legal Directory | This document is a template and does not constitute legal advice. Consult a licensed lawyer for your specific situation.
</div>
</body>
</html>`
    return NextResponse.json({
      ok: true,
      content: html,
      contentType: 'text/html',
      filename: `${slug}-${Date.now()}.html`,
    })
  }

  return NextResponse.json({
    ok: true,
    content: filled,
    contentType: 'text/plain',
    filename: `${slug}-${Date.now()}.txt`,
  })
}
